In [10]:
import pandas as pd
import requests

region_codes = ["EAS", "SAS"]

all_countries = []

for region in region_codes:
    url = f"https://api.worldbank.org/v2/region/{region}/country?format=json&per_page=500"
    response = requests.get(url)
    data = response.json()
    df_region = pd.DataFrame(data[1])
    all_countries.append(df_region)

countries_df = pd.concat(all_countries, ignore_index=True)
print(countries_df[['id', 'iso2Code', 'name']].head(30))

     id iso2Code                       name
0   ASM       AS             American Samoa
1   AUS       AU                  Australia
2   BRN       BN          Brunei Darussalam
3   CHN       CN                      China
4   FJI       FJ                       Fiji
5   FSM       FM      Micronesia, Fed. Sts.
6   GUM       GU                       Guam
7   HKG       HK       Hong Kong SAR, China
8   IDN       ID                  Indonesia
9   JPN       JP                      Japan
10  KHM       KH                   Cambodia
11  KIR       KI                   Kiribati
12  KOR       KR                Korea, Rep.
13  LAO       LA                    Lao PDR
14  MAC       MO           Macao SAR, China
15  MHL       MH           Marshall Islands
16  MMR       MM                    Myanmar
17  MNG       MN                   Mongolia
18  MNP       MP   Northern Mariana Islands
19  MYS       MY                   Malaysia
20  NCL       NC              New Caledonia
21  NRU       NR                      Nauru
22  NZL       NZ                New Zealand
23  PHL       PH                Philippines
24  PLW       PW                      Palau
25  PNG       PG           Papua New Guinea
26  PRK       KP  Korea, Dem. People's Rep.
27  PYF       PF           French Polynesia
28  SGP       SG                  Singapore
29  SLB       SB            Solomon Islands

In [11]:
asian_countries_df = countries_df[
    countries_df['region'].apply(lambda x: x['id'] in region_codes)
].copy()

asian_countries_df = asian_countries_df[
    asian_countries_df['id'].str.len() == 3
].copy()

print(asian_countries_df[['id', 'name']].head(20))
print(asian_countries_df.shape)

     id                      name
0   ASM            American Samoa
1   AUS                 Australia
2   BRN         Brunei Darussalam
3   CHN                     China
4   FJI                      Fiji
5   FSM     Micronesia, Fed. Sts.
6   GUM                      Guam
7   HKG      Hong Kong SAR, China
8   IDN                 Indonesia
9   JPN                     Japan
10  KHM                  Cambodia
11  KIR                  Kiribati
12  KOR               Korea, Rep.
13  LAO                   Lao PDR
14  MAC          Macao SAR, China
15  MHL          Marshall Islands
16  MMR                   Myanmar
17  MNG                  Mongolia
18  MNP  Northern Mariana Islands
19  MYS                  Malaysia
(43, 10)

In [12]:
country_codes = asian_countries_df['id'].tolist()
countries = ";".join(country_codes)

print(countries[:200])   
print(len(country_codes))  # how many countries

ASM;AUS;BRN;CHN;FJI;FSM;GUM;HKG;IDN;JPN;KHM;KIR;KOR;LAO;MAC;MHL;MMR;MNG;MNP;MYS;NCL;NRU;NZL;PHL;PLW;PNG;PRK;PYF;SGP;SLB;THA;TLS;TON;TUV;VNM;VUT;WSM;BGD;BTN;IND;LKA;MDV;NPL
43

In [13]:
# Life expectancy

indicator = "SP.DYN.LE00.IN"

url = f"https://api.worldbank.org/v2/country/{countries}/indicator/{indicator}?format=json&per_page=20000"

response = requests.get(url)
life_raw = response.json()

life_df_raw = pd.DataFrame(life_raw[1])
life_df_raw.head(20)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2025,NaN,,,0
1,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2024,72.992,,,0
2,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2023,72.852,,,0
3,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2022,72.752,,,0
4,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2021,72.708,,,0
5,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2020,72.672,,,0
6,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2019,72.751,,,0
7,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2018,72.794,,,0
8,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2017,72.801,,,0
9,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2016,72.640,,,0
10,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2015,72.654,,,0
11,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2014,72.687,,,0
12,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2013,72.769,,,0
13,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2012,72.709,,,0
14,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2011,72.662,,,0
15,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2010,72.587,,,0
16,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2009,70.839,,,0
17,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2008,72.430,,,0
18,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2007,72.365,,,0
19,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2006,72.397,,,0

In [14]:
# Under-5 mortality
indicator = "SH.DYN.MORT"
url = f"https://api.worldbank.org/v2/country/{countries}/indicator/{indicator}?format=json&per_page=20000"

response = requests.get(url)
mort_raw = response.json()
mort_df_raw = pd.DataFrame(mort_raw[1])

mort_df_raw.head()

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,"{'id': 'SH.DYN.MORT', 'value': 'Mortality rate...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2025,NaN,,,0
1,"{'id': 'SH.DYN.MORT', 'value': 'Mortality rate...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2024,NaN,,,0
2,"{'id': 'SH.DYN.MORT', 'value': 'Mortality rate...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2023,NaN,,,0
3,"{'id': 'SH.DYN.MORT', 'value': 'Mortality rate...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2022,NaN,,,0
4,"{'id': 'SH.DYN.MORT', 'value': 'Mortality rate...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2021,NaN,,,0

In [15]:
# Adolescent fertility
indicator = "SP.ADO.TFRT"
url = f"https://api.worldbank.org/v2/country/{countries}/indicator/{indicator}?format=json&per_page=20000"

response = requests.get(url)
fert_raw = response.json()
fert_df_raw = pd.DataFrame(fert_raw[1])

fert_df_raw.head()

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,"{'id': 'SP.ADO.TFRT', 'value': 'Adolescent fer...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2025,NaN,,,0
1,"{'id': 'SP.ADO.TFRT', 'value': 'Adolescent fer...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2024,34.749,,,0
2,"{'id': 'SP.ADO.TFRT', 'value': 'Adolescent fer...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2023,34.181,,,0
3,"{'id': 'SP.ADO.TFRT', 'value': 'Adolescent fer...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2022,34.104,,,0
4,"{'id': 'SP.ADO.TFRT', 'value': 'Adolescent fer...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2021,34.214,,,0

In [16]:
life = life_df_raw.copy()

life = life[['countryiso3code', 'date', 'value']]
life.columns = ['country_code', 'year', 'life_expectancy']

life['year'] = pd.to_numeric(life['year'], errors='coerce')
life['life_expectancy'] = pd.to_numeric(life['life_expectancy'], errors='coerce')

life = life[(life['year'] >= 1990) & (life['year'] <= 2024)]

life.head()

  country_code  year  life_expectancy
1          ASM  2024           72.992
2          ASM  2023           72.852
3          ASM  2022           72.752
4          ASM  2021           72.708
5          ASM  2020           72.672

In [17]:
mort = mort_df_raw.copy()

mort = mort[['countryiso3code', 'date', 'value']]
mort.columns = ['country_code', 'year', 'mortality_u5']

mort['year'] = pd.to_numeric(mort['year'], errors='coerce')
mort['mortality_u5'] = pd.to_numeric(mort['mortality_u5'], errors='coerce')

mort = mort[(mort['year'] >= 1990) & (mort['year'] <= 2024)]

mort.head()

  country_code  year  mortality_u5
1          ASM  2024           NaN
2          ASM  2023           NaN
3          ASM  2022           NaN
4          ASM  2021           NaN
5          ASM  2020           NaN

In [18]:
fert = fert_df_raw.copy()

fert = fert[['countryiso3code', 'date', 'value']]
fert.columns = ['country_code', 'year', 'fertility_adolescent']

fert['year'] = pd.to_numeric(fert['year'], errors='coerce')
fert['fertility_adolescent'] = pd.to_numeric(fert['fertility_adolescent'], errors='coerce')

fert = fert[(fert['year'] >= 1990) & (fert['year'] <= 2024)]

fert.head()

  country_code  year  fertility_adolescent
1          ASM  2024                34.749
2          ASM  2023                34.181
3          ASM  2022                34.104
4          ASM  2021                34.214
5          ASM  2020                34.149

In [19]:
# merge 
df = life.merge(mort, on=['country_code', 'year'], how='inner') \
         .merge(fert, on=['country_code', 'year'], how='inner')

df.head()
print(df.columns)

Index(['country_code', 'year', 'life_expectancy', 'mortality_u5',
       'fertility_adolescent'],
      dtype='str')

In [20]:
# missing values
df = df.sort_values(['country_code', 'year']).copy()

num_cols = ['life_expectancy', 'mortality_u5', 'fertility_adolescent']

df[num_cols] = (
    df.groupby('country_code')[num_cols]
      .transform(lambda x: x.interpolate())
)

In [21]:
df = df.dropna()

In [24]:
# add country names
country_map = dict(zip(asian_countries_df['id'], asian_countries_df['name']))

df['country'] = df['country_code'].map(country_map)
df[['country_code', 'country']].drop_duplicates().head(20)

    country_code                country
69           AUS              Australia
104          BGD             Bangladesh
139          BRN      Brunei Darussalam
174          BTN                 Bhutan
209          CHN                  China
244          FJI                   Fiji
279          FSM  Micronesia, Fed. Sts.
384          IDN              Indonesia
419          IND                  India
454          JPN                  Japan
489          KHM               Cambodia
524          KIR               Kiribati
559          KOR            Korea, Rep.
594          LAO                Lao PDR
629          LKA              Sri Lanka
699          MDV               Maldives
734          MHL       Marshall Islands
769          MMR                Myanmar
804          MNG               Mongolia
874          MYS               Malaysia

In [25]:
# reorder columns
df = df[['country', 'country_code', 'year',
         'life_expectancy', 'mortality_u5', 'fertility_adolescent']]

df = df.sort_values(['country_code', 'year']).reset_index(drop=True)

df.head()

,country,country_code,year,life_expectancy,mortality_u5,fertility_adolescent
0,Australia,AUS,1990,76.994634,9.2,22.426
1,Australia,AUS,1991,77.275610,8.7,22.274
2,Australia,AUS,1992,77.378049,8.2,22.306
3,Australia,AUS,1993,77.878049,7.7,21.245
4,Australia,AUS,1994,77.878049,7.3,20.965

In [26]:
df.to_csv("asian_population_clean.csv", index=False)

OSError: [Errno 30] Read-only file system: 'asian_population_clean.csv'